# Dev stuff
markdown:  rdiscount
safe:      true
lsi:       false
pygments:  true
exclude: ['node_modules', 'Gruntfile.js', 'package.json']


# Site stuff
permalink: /:categories/:title
charset:   utf-8
baseurl:   /
url:       http://thesearchfor.us

# Specific stuff
version:      0.0.1
date:         0000-00-00
language:     en-GB
license:      v2.0. http://www.apache.org/licenses/LICENSE-2.0

name:         The Search For Us
name_short:   SFU
name_safe:    the-search-for-us
tagline:      That others may live.
color:        #D83434
email:        gregdaynes@gmail.com
copyright:    © 2013 The Search For Us & Gregory Daynes. All rights reserved.
google:       UA-XXXXXXXX-X
creator:      Gregory Daynes
publisher:    http://twitter.com/gregdaynes
keywords:     list, of, keywords
description:  description of site
twitter:      gregdaynes
twitter_card: summary
