# Dev stuff
markdown:  rdiscount
safe:      true
lsi:       false
pygments:  true
host:      0.0.0.0
port:      4000


# Site stuff
permalink: /:categories/:title
charset:   utf-8
baseurl:   /sfu

# Specific stuff
version:      0.0.1
date:         0000-00-00
language:     en-GB
license:      v2.0. http://www.apache.org/licenses/LICENSE-2.0

name:         The Search For Us
name_short:   SFU
tagline:      Looking, so you don't have too
color:        #D83434
email:        gregdaynes@gmail.com
copyright:    © 2013 The Search For Us & Gregory Daynes. All rights reserved.
google:       UA-XXXXXXXX-X
creator:      Gregory Daynes
publisher:    http://twitter.com/gregdaynes
keywords:     list, of, keywords
description:  description of site
twitter:      gregdaynes
twitter_card: summary


###############
# Prose stuff
prose:
  rooturl: '_posts'
  siteurl: 'http://gregdaynes.github.io/sfu/'
  relativeLinks: 'http://gregdaynes.github.io/sfu/links.jsonp'
  media: '_posts/media'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
    _posts/gear:
      - name: "category"
        field:
          element: "hidden"
          value: "gear"
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""




### page details
# title
# description
# keywords
# graph_image
# graph_image_type
# graph_image_width
# graph_image_height
